### ISSUE TITLE
Adding Pan mode and Zoom on X/Y only modes

### ISSUE THREAD

**Issue by Beldramma** [newville/wxmplot#41]
Hi.
I am working adding these modes, that we can find with matplotlib. With the current program, it seems to me that I cannot add zoom only on X/Y functions in the zoom functions which already exist, so I will add two new cursors modes for these functions. Currently I am working on zoom on x mode, I am trying to create a rectangular box with its height equal to the height of the graph, but I don't know how to get back these values. 
For pan mode, I tried to use the pan function from the Navigation toolbar from matplotlib.

**Comment by Beldramma** [comment]
Added Pan button which is functional but when we come back to zoom mode, we do not have a zoom cursor icon. It's not a cursor mode like 'report' or 'zoom', here I use the pan function from the Navigation toolbar from matplotlib. When I activate this function, I put the cursor mode in 'report'.

**Comment by Beldramma** [comment]
All these changes are located in the branch 'Antoine Kristanek'. I tested my Pan function in a multiframe, it works in the windows where I panned, but if I go in another frame, I need to activate again Pan mode.

**Comment by Beldramma** [comment]
Succeeded to finish zoom on X/Y modes. I succeeded to keep the cursor icon like before. In multiframe, I have a problem, because it works in the first frame, but not in others.

**Comment by newville** [comment]
@Beldramma is it your intention to make a Pull Request from the branch you are working on?  

If I understand correctly, you are working in https://github.com/Beldramma/wxmplot/tree/Antoine_Kristanek.  Is that correct?  That branch has an enormous number of changes -- it looks like you included a whole environment with like 1700 files or something.   That's not ever going to be merged in.  

Please make small changes and then Pull Requests as you go.  I have been on other projects and have not looked at any of your changes.

**Comment by newville** [comment]
@Beldramma  I think this is now resolved.  I merged your pull request #43 and then made a few changes on top of that.  In the current master branch:

Zoom can be toggled between "both X/Y", "X only", and "Y only" with Ctrl-W, Ctrl-X, and Ctrl-Y or from the radio button (ie, choose one of the three choices) in the options menu.   I think that works well. 

For Panning, I went with not having a separate pan-or-zoom mode and just bound the arrow keys (up/down/left/right) to add to the list of zoom limits.  That is, hitting an arrow key will add a new zoom level (so that un-zooming with Ctrl-Z will walk back through the pan and zoom views).    By default, the arrow keys move the view by 2% (which may not seem like much but is definitely noticeable), but you can keep pressing the arrow key or use Shift-arrow to move by 10% of the view.

**Comment by Beldramma** [comment]
I executed my program, I can see your changes for the buttons, but after that I zoomed, I tried to pan with arrow keys, but nothing happened.

**Comment by Beldramma** [comment]
It is a windows with interactive.

**Comment by newville** [comment]
@Beldramma  It works for me, but I have not been able to try all platforms.  What versions and OS are you using?  Provide an example script that shows the problem.

**Comment by Beldramma** [comment]
Sure. I used it on Windows 10, and the last version of wxmplot that I directly cloned.

**Comment by Beldramma** [comment]
I sent you the script by mail.

**Comment by Beldramma** [comment]
Ok let's continue the discussion here finally, it will be better for us to find that if we need it in the future. So like you adviced me, I tried to debug the code to know why the keys arrows didn't work for me. So I simply put some print in the __onKeyEvent function, one at the really beginning, and one for each arrow key. I put also a print in the basepanel init, so I can check if I use the good version of the code. I ran different examples, multiplot, plot_many_traces, plotapp, scatterplot and stackedplot. For each of them, sames results : I can see that I use the good version of wxmplot, I see a print if i push Ctrl button, or another button, but I can also see that when I push any arrow key, I never entered in __onKeyEvent. Others keys events work, ctrl-x, ctrl-y, ctrl-w, even if I push a random letter, i entered in __onKeyEvent. I did that with Spyder, to debug my program. I use the same examples than you, I will search deeper.

**Comment by newville** [comment]
Can you explain what "I did that with Spyder" means?   Does that mean that you are running these scripts somehow from within Spyder?  I'm not sure I don't know how that works, exactly.  I can certainly believe that an environment like Spyder would capture some keyboard events.  Anyway,  what happens if you don't run from within Spyder but just as a python script from a plain terminal?

**Comment by newville** [comment]
I suggest printing the characters that *do* get pressed:
    
      key = event.guiEvent.GetKeyCode()
      print("Key pressed : ", key)

**Comment by Beldramma** [comment]
> 
> 
> Can you explain what "I did that with Spyder" means? Does that mean that you are running these scripts somehow from within Spyder? I'm not sure I don't know how that works, exactly. I can certainly believe that an environment like Spyder would capture some keyboard events. Anyway, what happens if you don't run from within Spyder but just as a python script from a plain terminal?

Yeah, I ran these scripts from Spyder. I tried to run them directly launching them from a cmd, but I had some errors messages. 
Ok I will do that.
